"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Select = exports.Insert = exports.Click = exports.Screenshot = exports.Remember = exports.Open = exports.Action = void 0;
var Action_1 = require("./Action");
Object.defineProperty(exports, "Action", { enumerable: true, get: function () { return Action_1.Action; } });
var Open_1 = require("./Open");
Object.defineProperty(exports, "Open", { enumerable: true, get: function () { return Open_1.Open; } });
var Remember_1 = require("./Remember");
Object.defineProperty(exports, "Remember", { enumerable: true, get: function () { return Remember_1.Remember; } });
var Screenshot_1 = require("./Screenshot");
Object.defineProperty(exports, "Screenshot", { enumerable: true, get: function () { return Screenshot_1.Screenshot; } });
var Click_1 = require("./Click");
Object.defineProperty(exports, "Click", { enumerable: true, get: function () { return Click_1.Click; } });
var Insert_1 = require("./Insert");
Object.defineProperty(exports, "Insert", { enumerable: true, get: function () { return Insert_1.Insert; } });
var Select_1 = require("./Select");
Object.defineProperty(exports, "Select", { enumerable: true, get: function () { return Select_1.Select; } });
